# Generated by Django 3.2.8 on 2021-10-22 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do projeto')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de término')),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor do projeto')),
                ('correct_answer', models.CharField(choices=[('0', 'Baixo'), ('1', 'Médio'), ('2', 'Alto')], max_length=1, verbose_name='Risco ')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projects_project',
            },
        ),
    ]
