# Generated by Django 3.2.8 on 2021-10-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='correct_answer',
            new_name='risk',
        ),
    ]
