# Generated by Django 3.2.8 on 2021-10-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='risk',
            field=models.CharField(choices=[('5', 'Baixo'), ('10', 'Médio'), ('20', 'Alto')], max_length=2, verbose_name='Risco'),
        ),
    ]
